### ISSUE TITLE
LCD show Wspd:0

### ISSUE THREAD

**Issue by U-Smiles** [vladajankovic/STM32F103R6-MCU-project#2]
![image](https://github.com/vladajankovic/STM32F103R6-MCU-project/assets/105765048/cfc824a9-1dbf-4d93-b5c4-e5ac7017c459)
why it always show ''0''?

and I can't find sensor RAINGAUGE in my protues library
![image](https://github.com/vladajankovic/STM32F103R6-MCU-project/assets/105765048/f2e91a94-877d-4164-aed0-eeed40eeea3c)

**Comment by vladajankovic** [comment]
For the Wind Speed problem, I suggest you use the debugger and traverse the code for calcualting the variables for Wind Speed step by step.
Our course assistant gave us an updated folder MODELS to paste in the Proteus installation folder. Maybe it contained certain models like the RAINGAUGE that you were unable to find.

**Comment by U-Smiles** [comment]
ok,i update to protues 8.17 find raingauge sensor
and checking driver_lcd.c && driver_anemo.c
